AppBundle\Entity\Theme:
    type: entity
    table: theme
    id:
        idtheme:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: IdTheme
            generator:
                strategy: IDENTITY
    fields:
        theme:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            column: Theme
    lifecycleCallbacks: {  }
